### ISSUE TITLE
ndt: make sure we use both single and multi stream

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-android#120]
By using both, we can more accurately measure the last mile bandwidth and the quality of the internet connection. The sad truth is that there is a little bit of an indetermination-principle-like problem with measuring speed, where, if you measure the last mile more accurately (with parallel streams) you end up not understanding very well if there's congestion in the backhaul. And the other way round.

**Comment by lorenzoPrimi** [comment]
How to achieve this in the app?

**Comment by hellais** [comment]
cc @bassosimone

**Comment by bassosimone** [comment]
Thanks for mentioning me explicitly, I did miss this issue. I believe it is not worth investing any effort in this topic, because ndt7 will achieve a more precise bandwidth measurement with a single stream.

Hence, I am going to close this issue. It made sense when I opened it, not it's superseded by the future, and hence it should be moved to the Attic.
