### ISSUE TITLE
Web connectivity website descriptions

### ISSUE THREAD

**Issue by spikie1** [ooni/probe-android#142]
I think you should include a basic description of each web site on the web connectivity section so people know what sort of sites are actually been blocked

**Comment by EvasivePangolin** [comment]
Seconded. It'd be nice for people on networks that censor 'explicit content' (such as schools) to be able to easily see what that network has defined as explicit.

**Comment by lorenzoPrimi** [comment]
In the 2.0 apps every site have a category (such as PORN, LGBT, NEWS..)
The user will be able to choose which categories of websites to test

**Comment by lorenzoPrimi** [comment]
Closing as now every website category is showed in the result list.
