### ISSUE TITLE
Clients should never register twice

### ISSUE THREAD

**Issue by hellais** [ooni/probe-android#151]
Currently the OONI Probe Android app will sometimes end in a race condition and registering twice or even more times.

The apps should have a mutex lock for registration requests and wait on the lock before issuing another request to create an account.

On Android I see that there are 90'000+ duplicate accounts.

xref: https://github.com/ooni/probe-ios/issues/180

**Comment by lorenzoPrimi** [comment]
fixed in https://github.com/ooni/probe-android/pull/159/commits/330b73771cab60859918f8b2d3696870f2c6f3b3
