### ISSUE TITLE
Web Connectivity description is not scrollable

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe-android#164]
The Web Connectivity description, provided once you tap on the Websites card, is not scroll-able and as a result, you can't read the entire description in the app. 

See: 

![web-connectivity](https://user-images.githubusercontent.com/8290574/49666615-eae8ee00-fa58-11e8-8462-2a3526650b0d.jpeg)

**Comment by hellais** [comment]
cc @xanscale @lorenzoPrimi

**Comment by xanscale** [comment]
fixed with https://github.com/ooni/probe-android/commit/f962253a9cc16aca143b762d5058175666838276
