### ISSUE TITLE
Translated text is truncated in settings and onboarding

### ISSUE THREAD

**Issue by hellais** [ooni/probe-android#169]
As reported by a translator the following pieces of text appear truncated in the app:

* [ ] Text labels inside of the settings page
* [ ] Text in the onboarding

We should either set more strict character limits on the source strings or find a way to make the text be all readable (for example making the labels in the settings flow on two lines).

See screenshots:

![screenshot_20190107-132019_ooni_probe](https://user-images.githubusercontent.com/424620/50793219-55c56780-132c-11e9-8faf-ec8537495be1.png) ![screenshot_20190107-140343_ooni_probe](https://user-images.githubusercontent.com/424620/50793221-55c56780-132c-11e9-8857-f5b90c4be4b1.png) ![screenshot_20190107-145508_ooni_probe](https://user-images.githubusercontent.com/424620/50793223-565dfe00-132c-11e9-811a-5a28b8346a84.png)

**Comment by lorenzoPrimi** [comment]
Also "The second welcome screen displays "Things to know" in English and needs
to be translatable in Transifex."

**Comment by xanscale** [comment]
Text labels inside of the settings page must be short, i can't put in multiple row.

About Text in the onboarding we have 3 option:
1) make text shoter
2) make text anchor to bottom: in small screen and long text we can have TITLE over the header image
3) reduce margin and size: they could remain cases in which you see badly

@hellais choose :D

**Comment by hellais** [comment]
@xanscale is it not possible to make the text area scrollable with the buttons at the bottom if the screen is too small?

I also think this is a question for @elioqoshi.

**Comment by xanscale** [comment]
@hellais yes, is another option. (named 4)

personally i continue to prefer option 2

wait @elioqoshi verdict

**Comment by lorenzoPrimi** [comment]
We tried scrollable text and looked really bad. 
Plus the buttons ( and the steps) should always be visible at the bottom of the screen

**Comment by lorenzoPrimi** [comment]
Do 2 for now. There is no time

**Comment by lorenzoPrimi** [comment]
This won't be fixed in 2.0. The workaround will probably be to insert that text in a scrollview for smaller device.
In the next version we'll address better this issue

**Comment by elioqoshi** [comment]
@lorenzoPrimi can we revisit this?

**Comment by lorenzoPrimi** [comment]
@elioqoshi we added a scrollview for smaller devices. I think it's so far the best solution unless you have something better in mind

**Comment by elioqoshi** [comment]
I will do some testing on a test device I have and see if we can do anything better than that. @lorenzoPrimi @xanscale is it possible to have a different text size for these small resolutions?

**Comment by lorenzoPrimi** [comment]
@elioqoshi we tried but it's not worth it, their screen is already small and the resolution is very bad, so shrinking the text will make it unreadable

**Comment by elioqoshi** [comment]
That makes sense.

**Comment by emmapeel2** [comment]
can you have different text sizes for different languages? French and Spanish, for example, tend to need more space than English

**Comment by lorenzoPrimi** [comment]
@emmapeel2 it all goes back to my last comment, a small screen has also a low resolution, making the font smaller will make it unreadable.
@elioqoshi test the actual version with scrollview, if you are satisfied we can close this ticket

**Comment by lorenzoPrimi** [comment]
Tested again. This was already fixed by using a scrollview.
![scroll1](https://user-images.githubusercontent.com/1616097/71408507-d022f080-263e-11ea-9236-6f86f4c4ee65.png)
![scroll2](https://user-images.githubusercontent.com/1616097/71408508-d022f080-263e-11ea-9987-a3dcfacd4f50.png)
