### ISSUE TITLE
Wrong title in the second step of the onboarding

### ISSUE THREAD

**Issue by hellais** [ooni/probe-android#172]
The second step of the onboarding says "Things to know", while it should instead say "Heads-up" (the value of the strings key `Onboarding.ThingsToKnow.Title`).

This only affects Android.

**Comment by lorenzoPrimi** [comment]
fixed in https://github.com/ooni/probe-android/commit/73e8f03aca8e2ad04c184c5bf9fc0f11e5b1fa18
