### ISSUE TITLE
Create 2.0.0 F-Droid build

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe-android#175]
To create a new build in F-Droid you can use the master branch and build the fdroid flavor.
There is no need to use a separate branch, the master branch now has two different flavors, fdroid and full. The fdroid flavor strips out all the proprietary dependencies. 

Also description needs to be updated to reflect the last changes in https://play.google.com/store/apps/details?id=org.openobservatory.ooniprobe

**Comment by lorenzoPrimi** [comment]
@eighthave can do it or you give us instruction on how to do it?
Also is this new "flavor" method a good way to do this?

**Comment by eighthave** [comment]
To update the description, you can submit a merge request on this file:
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.openobservatory.ooniprobe.txt

I think some projects are using a _fdroid_ gradle flavor, but I haven't done it personally.  @izzysoft @vanitasvitae @bubu or @licaon-kter might know better than me.

**Comment by licaon-kter** [comment]
Looking at it now...

**Comment by licaon-kter** [comment]
Done, https://gitlab.com/fdroid/fdroiddata/commit/c16ea63a7667867b5589c80539c6ad3d2f94b5c3

**Comment by bassosimone** [comment]
@licaon-kter thanks! A small nit:

> Repo: https://github.com/TheTorProject/ooniprobe-android

Should actually be: https://github.com/ooni/probe-android

(What is the implication of disabling AUM wrt future updates? Should we ping you directly at least for next update so to disable AUM?)

**Comment by eighthave** [comment]
how about adding the reproducible build _disorderfs_ hack?  This forces
the build to run with a sorted filesystem, which works around the bugs
in the Android tools.  So far, we haven't had any problems with it, and
its easy to add.

**Comment by licaon-kter** [comment]
@bassosimone It redirects now, will fix.

**Comment by bassosimone** [comment]
@licaon-kter IIRC the rationale was to bind a specific version `1.2.3` to a specific build `+4`, but my jet lagged brain could be failing me. I'm sure either @lorenzoPrimi or @hellais could correct me in case my recollection is wrong.

**Comment by hellais** [comment]
@licaon-kter does the build number in the tag create issues to the F-Droid integration?

I would like to better understand why as the presence of a build number in a tag is a supported feature of semantic versioning (https://semver.org/#spec-item-10).

**Comment by licaon-kter** [comment]
It does, unfortunately.

**Comment by eighthave** [comment]
Seems to me a that a build number should be added only by the build, not to a git tag.  The git tag should never change, it'll always point to the same commit, regardless of how many times you build it.

**Comment by lorenzoPrimi** [comment]
Thanks for the suggestion, we are gonna do like you said and remove the build number.

Can this issue be closed? Was the 2.0.0 published on fdroid?

**Comment by licaon-kter** [comment]
Will be on the next cycle, 1-2 days hopefully.

**Comment by elioqoshi** [comment]
Thanks @licaon-kter, it's live!

**Comment by lorenzoPrimi** [comment]
v2.0.1 has been tagged

**Comment by licaon-kter** [comment]
@lorenzoPrimi 
FYI, https://gitlab.com/fdroid/fdroiddata/commit/fcd5935a0748cd00f4d0545d4c91712853f9d027

**Comment by hellais** [comment]
@licaon-kter 
Does
```
AutoUpdateMode: Version v%v
```
mean that if we make a tag with the format `vX.Y.Z` it will automatically update the f-droid app version to that?

How long should we expect it to take to recognise the tag and publish it?

**Comment by licaon-kter** [comment]
@hellais You're already doing it...keep on... :)

Yes, usually 1-2 days, it depends... I mean it gets picked up at the start of cycle, when the cycle finishes is the unknown, what other apps are to be build, if any issues arise, etc.

**Comment by hellais** [comment]
@licaon-kter gotcha, thanks!

I was just wondering on the timing to know when, if at all, we should look into bugging you if we don't see it appearing in F-Droid.

From what I gather, probably everything is fine unless a week has passed since the tag and we don't see it on f-droid yet.

**Comment by licaon-kter** [comment]
@hellais 

Current global build cycle (almost realtime, UTC): https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500

Last app build log: https://f-droid.org/wiki/index.php?title=org.openobservatory.ooniprobe/lastbuild&redirect=no
