### ISSUE TITLE
The app should allow to see logs even with an invalid JSON measurement

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe-android#196]
Community members in Senegal reported some of their performance tests (NDT & DASH) didn't render any results (with "N/A" being displayed in the results for these tests). This was reportedly a temporary problem, which only occurred a few times (in other instances, the tests have worked properly since).

This bug occurred on OONI Probe Android 2.0.2, MK 0.9.3.

The log they shared:

{
  "annotations": {
    "engine_name": "libmeasurement_kit",
    "engine_version": "0.9.3",
    "engine_version_full": "v0.9.3",
    "flavor": "full",
    "network_type": "wifi",
    "platform": "android"
  },
  "data_format_version": "0.2.0",
  "id": "b0cd3cfc-d096-415b-8230-976a701820bb",
  "input_hashes": [],
  "measurement_start_time": "2019-02-23 17:35:00",
  "options": [],
  "probe_asn": "AS8346",
  "probe_cc": "SN",
  "probe_ip": "127.0.0.1",
  "report_id":
"20190223T173501Z_AS8346_cpdtu5WwKRNTIzyBnfnYXEWkmdHLZWzZWoGMV0rm7umklV60SP",
  "software_name": "ooniprobe-android",
  "software_version": "2.0.2",
  "test_helpers": {},
  "test_keys": {
    "client_resolver": "213.154.64.5"
  },
  "test_name": "dash",
  "test_runtime": 65.12594199180603,
  "test_start_time": "2019-02-23 17:34:56",
  "test_version": "0.7.0"
}

Contacting bouncer: https://bouncer.ooni.io
Using discovered collector: https://b.collector.ooni.io:443
Your country: SN
Your ISP identifier: AS8346
Your ISP name: Autonomous System
Results collector: https://b.collector.ooni.io:443
Opening report; please be patient...
Report ID:
20190223T173501Z_AS8346_cpdtu5WwKRNTIzyBnfnYXEWkmdHLZWzZWoGMV0rm7umklV60SP
Discovering mlab server using mlabns
Discovered mlab test server: neubot.mlab.mlab1.los01.measurement-lab.org
Negotiating with: neubot.mlab.mlab1.los01.measurement-lab.org
Start dash test with: http://neubot.mlab.mlab1.los01.measurement-lab.org/
Connected to server (3WHS RTT = 1.295946 s); starting the test
dash: cannot receive response: generic_timeout_error
Test complete; closing connection
neubot: test failed: generic_timeout_error
Collecting results
Submitting test results; please be patient...
Results successfully submitted
Closing report; please be patient...
Report successfully closed

The same issue was also reported by others in Cuba: https://twitter.com/jadolg91/status/1100414929209683968 (the tweet includes a screenshot that shows the problem)

**Comment by bassosimone** [comment]
This is a MK bug. See: https://github.com/measurement-kit/measurement-kit/issues/1758

**Comment by bassosimone** [comment]
(We cannot say much on the Cuban case, except that there is a failure. I think we should ask for the logs in that case as well, otherwise we may classify unrelated bugs togeher; AFAIK, DASH and NDT cannot work in Cuba because mlabns doesn't work there. In both cases there is a missing field in the JSON that prevents the app from showing that a failure occurred. So, the bug is probably the same, but I am not sure we can successfully conclude it's the same bug before we see the logs.)

**Comment by bassosimone** [comment]
I've asked on Twitter whether it's possible to see the logs to confirm my above guess. Thanks!

**Comment by bassosimone** [comment]
Changed my mind. This is not a duplicate. The app should behave when the JSON is malformed.

**Comment by bassosimone** [comment]
See also ooni/probe#850

**Comment by bassosimone** [comment]
Closing since we have an umbrella ticket.
