### ISSUE TITLE
Markdown syntax is exposed in German test descriptions of the Performance test

### ISSUE THREAD

**Issue by elioqoshi** [ooni/probe-android#199]
Markdown syntax is exposed in German test descriptions of the Performance test:

![image](https://user-images.githubusercontent.com/5436686/53497728-1c47e780-3aa5-11e9-80ad-98bdd793a7c8.png)

This is probably related to the German translation as it doesn't happen with French for example.

**Comment by lorenzoPrimi** [comment]
The text doesn't respect the markdown sintax: no space between ] and ( 
It should be modified in transifex

**Comment by lorenzoPrimi** [comment]
@hellais should I manually fix it in transifex or we add something to the string script to check these cases?

**Comment by elioqoshi** [comment]
> The text doesn't respect the markdown sintax: no space between ] and (
It should be modified in transifex

It seems to be correct in Transifex and from what I can tell there is also a space in the app between the 
between ] and (

> should I manually fix it in transifex or we add something to the string script to check these cases?

It was correct as far as I can tell: https://www.transifex.com/otf/ooniprobe/translate/#de/strings-json/158100856

But in any case, a script for these cases which can be easily overlooked might save time in the future (if not ours, our translators at least)

**Comment by lorenzoPrimi** [comment]
Nope, it's not correct. look the part in German, it has the space

**Comment by elioqoshi** [comment]
> Nope, it's not correct. look the part in German, it has the space

Sorry I thought you meant that it needs to have the space (forgot Markdown syntax for a sec)

**Comment by hellais** [comment]
> should I manually fix it in transifex or we add something to the string script to check these cases?

I would suggest manually fixing the source string in transifex (we still want the text to be correct in transifex), but since this is a common mistake translators make, perhaps we should add a check to the script which downloads the translations to ensure no other strings contain the same issue.

For reference this was a similar issue in the french translation: https://github.com/ooni/probe/issues/842

**Comment by elioqoshi** [comment]
Closing this issue then. Feel free to open another issue if the script will be added later on.

**Comment by hellais** [comment]
Let's keep this open until the bug is fixed in the app.

**Comment by lorenzoPrimi** [comment]
Bug present in French, German, Portuguese and Hindi
<img width="301" alt="screenshot 2019-03-01 at 08 18 45" src="https://user-images.githubusercontent.com/1616097/53607680-ba00fb00-3bfa-11e9-8bca-2a6751d1dd95.png">

**Comment by lorenzoPrimi** [comment]
Fixed all languages in transifex and redownloaded languages in the app.
https://github.com/ooni/translations/commit/043ad3ef2a2558baefddcbdaaeb5f6ed8ce66463
https://github.com/ooni/probe-android/commit/a0fb68ea9cce6100a137b90251383ab468c261c7
https://github.com/ooni/probe-ios/commit/71d41a1cbaf195313380318956be31ddec60ca17
