### ISSUE TITLE
Improve UI for Run Custom URLs view

### ISSUE THREAD

**Issue by elioqoshi** [ooni/probe-android#200]
The current view of running a custom URL list in Android looks messy and lacks hierarchy while also not having the right Material Design feel to it. I'd propose to tweak this and make it clearer what can be done here. I propose 2 solutions (I'm fan of #2)

![image](https://user-images.githubusercontent.com/5436686/53512611-78216900-3ac3-11e9-8845-9ea78595b93e.png)

Figma File here:
https://www.figma.com/file/00SblzFT4mbq50wiBS1c3Wat/Probe-Android-Explorations?node-id=0%3A1

@holantonela what do you think?

**Comment by elioqoshi** [comment]
(For the record, you might notice the middle-aligned header titles. They are proposed in this issue: https://github.com/ooni/probe-android/issues/197 )

**Comment by xanscale** [comment]
![device-2019-02-27-224304](https://user-images.githubusercontent.com/255819/53525503-3d7af900-3ae2-11e9-9312-81e7cd381575.png)
actual situation of branch material

**Comment by elioqoshi** [comment]
Thanks @xanscale That is a great start! Let's get some more feedback on this before moving forward.

_P.S: I edited your comment with a more narrow image as otherwise it fills up the screen height._

**Comment by elioqoshi** [comment]
@lorenzoPrimi can we triage this? This is not urgent of course, but you are aware of the priorities better than me

**Comment by lorenzoPrimi** [comment]
I guess it can be done for 2.1.
Let's decide which one to use and then @xanscale will start implementing it.

**Comment by xanscale** [comment]
Consider this ui suggestions:
1 move run button on top right, on actionbar, as tick icon
2 move add test button on floating action button on bottom right

**Comment by elioqoshi** [comment]
@xanscale, as said on Slack, I don't think that's the best move since based on my discussions with @agrabeli I'm pretty sure users will have trouble understanding they can run the list by tapping an icon in the corner.  A button with text is clearer.

If we go that way, that leaves no space for 2) as there would already be a button in the bottom.

Hence

**Comment by elioqoshi** [comment]
@xanscale same here as well. Please update in a human readable form on the status of it instead of only the commit referencing it. Thanks!

**Comment by elioqoshi** [comment]
@xanscale the text size is off here. The Run button should be bigger and the URL count should be smaller.

![image](https://user-images.githubusercontent.com/5436686/54086374-30170780-4349-11e9-94e1-999895514a5b.png)

Also, is the round button an icon button with a text label instead? As upon touch it seems circular:
![image](https://user-images.githubusercontent.com/5436686/54086412-710f1c00-4349-11e9-8c4c-c167426ea7dd.png)

**Comment by elioqoshi** [comment]
Let's move ahead with it for now.

**Comment by lorenzoPrimi** [comment]
Ok so can it be merged and released?

**Comment by elioqoshi** [comment]
Yes
