### ISSUE TITLE
Test cards should not be configured to not test any test

### ISSUE THREAD

**Issue by elioqoshi** [ooni/probe-android#205]
Currently it's possible to disable every test in the `Configure Test` screen. When that Test Card is run then, nothing happens and a new test result row with no data is created. 

## Example 
Performance Test with NDT and DASH tests disabled:

### Configure Screen
![image](https://user-images.githubusercontent.com/5436686/54023343-05844d80-4195-11e9-8482-2cb1687cb593.png)

### Results:
![image](https://user-images.githubusercontent.com/5436686/54021124-b7b91680-418f-11e9-8379-01cf95756b3d.png)

### Test Summary
![image](https://user-images.githubusercontent.com/5436686/54021167-d28b8b00-418f-11e9-8262-9c601fa40d20.png)

## Proposed Solution:

If a test card is configured to not test any test, that test card should be able to be run. When the user attempts to `Run`, a modal should appear with the text (or something along these lines @agrabeli )

`No test types enabled for this test class. Please enable at least one first.`
[ OK ]

**Comment by lorenzoPrimi** [comment]
This is already what is done in iOS: when you attempt to disable a test you get this error `Modal.CantDeactivate` =  `Can't deactivate`
and the option gets re enabled

**Comment by elioqoshi** [comment]
Cool. So this only applies to Android then. @xanscale

**Comment by elioqoshi** [comment]
An alternative to this is to not allow the user to disable all tests in the Configure Screen. A modal with `Please enable at least one test` can prevent this.

**Comment by xanscale** [comment]
on android is very hard to lock disable of last test, i can easly show a popup/dialog when run test suite with all disabled.

if this option are good i need a string for that

**Comment by elioqoshi** [comment]
@xanscale I'd dislike doing a hack like that for not a greater reason. We should strive to use the same pattern for both iOS and Android. Could you check doing the same implementatio @lorenzoPrimi is doing on iOS? What would be a blocker?

**Comment by xanscale** [comment]
actually preference screen know nothing about test, is just a list of preference. the problem is that in Instant Messaging we have 1 preference more thant test (advanced WhatsApp).

anyway is not impossible, is just 5 minutes vs 4 hours :D

**Comment by elioqoshi** [comment]
> anyway is not impossible, is just 5 minutes vs 4 hours :D

I'm in favor of doing it right, no matter how long it takes. @lorenzoPrimi should take the final decision on this though.

> the problem is that in Instant Messaging we have 1 preference more thant test (advanced WhatsApp).

The subsetting of the WhatsApp test should not count (it can't be activated without activating its parent setting anyway)

**Comment by xanscale** [comment]
found a relative simple way, the question is only about how important it was

**Comment by lorenzoPrimi** [comment]
@xanscale when there is a ticket opened (and assigned) is to be done. 
When a ticket is tagged "low hanging" or "low priority" then it can be done in the future or a workaround can be used.
Of course if there is not a strict deadline and you want to take a few days to think if you can find a better or easier solution, that is the best way to do!

**Comment by lorenzoPrimi** [comment]
Tested and working
