### ISSUE TITLE
Upload version 2.0.3 to F-Droid

### ISSUE THREAD

**Issue by anadahz** [ooni/probe-android#207]
The [F-Droid OONI Probe](https://f-droid.org/en/packages/org.openobservatory.ooniprobe/) version is not in sync with the latest version `2.0.3`.

Ideally an automatic process should be used to keep versions in sync across all app stores.

**Comment by lorenzoPrimi** [comment]
From my understanding there is already an automated process, I tagged the `2.0.3` 
@licaon-kter do you confirm?

**Comment by licaon-kter** [comment]
You can check yourselves... 2.0.3 has been published 10 days ago.

/close this
