### ISSUE TITLE
Refactor ConfirmDialogFragment

### ISSUE THREAD

**Issue by hellais** [ooni/probe-android#218]
Currently the `ConfirmDialogFragment` can use with some important refactoring as discussed in https://github.com/ooni/probe-android/pull/214#discussion_r277609726.

Here is what I wrote in that PR

The fingerprint of this function also seems pretty tricky, perhaps some improvements can be made to make the argument count smaller?

**Comment by lorenzoPrimi** [comment]
I guess this was addressed, @bassosimone confirm?

**Comment by bassosimone** [comment]
Yes
