### ISSUE TITLE
Generate apk using Android Bundle

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe-android#239]
**Unoptimized APK**
*Warning:*

This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimizing your app for device configurations, your app is larger to download and install on users' devices than it needs to be. Larger apps see lower install success rates and take up storage on users' devices.

*Resolution:*

Use the [Android App Bundle](https://developer.android.com/platform/technology/app-bundle) to automatically optimize for device configurations, or manage it yourself with multiple APKs.

**Comment by bassosimone** [comment]
Yeah, we should investigate that!

**Comment by lorenzoPrimi** [comment]
Bundle `.aab` generated . for `2.1.0`.
Bundle size: 21.3 MB
Apk size: 22 MB
Unfortunatelly I can't upload it:
```
Upload failed
To upload an Android App Bundle you must be enrolled in App Signing by Google Play.
```
Then going to that page
```
Let Google manage and protect your app signing key
Only the account owner can accept the Terms of Service. Please ask the owner to do it. The contact email address is [HIDDEN_FOR_PRIVACY].
```
@hellais

**Comment by hellais** [comment]
I checked and it seems like we need the admins at guardian project to opt-in for this. I will send an email to Nathan.

**Comment by lorenzoPrimi** [comment]
Closing as we already use .aab
