### ISSUE TITLE
Web connectivity:  Test duration is not respected

### ISSUE THREAD

**Issue by anadahz** [ooni/probe-android#259]
##  Expected Behavior
Run a Web Connectivity test with a duration >< 120 seconds (for instance 1000 seconds).

## Actual Behavior

Web connectivity runs with the default test duration of 120 seconds.

## Steps to Reproduce the Problem

  1. Tap Web connectivity (Websites) card
  2. Tap on the settings icon
  3. Set the `Test duration` to a non default value

## Specifications

  - Version: 2.1.0
  - Platform: Android 7.1.2
  - Subsystem: measurement-kit 0.10.4

**Comment by hellais** [comment]
This does not occur in iOS, where when I set a maximum runtime also the estimated runtime in the card is updated.

@anadahz is using the OONI Probe build from f-droid yet I confirm that this bug is present also in the normal Android play store build.
