### ISSUE TITLE
Publish app apk to github release

### ISSUE THREAD

**Issue by hellais** [ooni/probe-android#261]
We would like to add a direct link to download the OONI Probe app apk on Android to our website (see: https://github.com/TheTorProject/ooni-web/issues/277).

It would be great if during the release process we add an extra step about uploading the built apk to the relevant github release.

**Comment by lorenzoPrimi** [comment]
The full apk or the stripped fdroid one?

**Comment by lorenzoPrimi** [comment]
@hellais can you explain this more in detail? Should I attach a signed apk (not fdroid) to the github release?
Also now we will generate an `aab` (Android Bundle) for Google Play, should I attach this as well?

**Comment by hellais** [comment]
This should be an apk that is installable on any Android device even those which don't have google play store on them.

It's for circumstances in which there may not be a play store in the country of the user and they need to install it.

Ideally the apk would be signed so that at least some level of verification is done prior to installation.

**Comment by lorenzoPrimi** [comment]
My question was slightly different, should I attach the apk of the fdroid version or the "full" version?
Sure I will sign the apk with the publish key.

**Comment by bassosimone** [comment]
@lorenzoPrimi the fdroid version because of "This should be an apk that is installable on any Android device even those which don't have google play store on them."

**Comment by lorenzoPrimi** [comment]
Done in https://github.com/ooni/probe-android/releases/tag/v2.2.0
