### ISSUE TITLE
f-droid: make oonimkall available using JCenter (or similar repos)

### ISSUE THREAD

**Issue by licaon-kter** [ooni/probe-android#328]
`ERROR: Found unknown maven repo 'https://dl.bintray.com/ooni/android/' at build.gradle`

These libs are not available [anywhere else](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L100)? Then maybe we'll need to build them...

**Comment by bassosimone** [comment]
I tried to make them available to Bintray JCenter and the process failed saying the POM file format was not valid. I did not bother with trying again because that repo was working for us.

```XML
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.ooni</groupId>
  <artifactId>oonimkall</artifactId>
  <version>2020.05.14-133636</version>
  <packaging>aar</packaging>
</project>
```

[This stackoverflow answer](https://stackoverflow.com/questions/52459232/invalid-pom-project-file-when-sending-request-to-include-bintray-package-in-jcen) highlights some of the reasons why JCEnter could reject a POM. So, maybe I can try and add them, and retry to make the package available through JCenter. (In the past, a POM like that was okay, so I believe they may have made their rules a bit more strict.)

Thanks for letting us know.

**Comment by bassosimone** [comment]
Made some progress by making the JCenter like our POM: https://github.com/ooni/probe-engine/pull/667.

**Comment by bassosimone** [comment]
We should be able to fix this within the next two weeks. Now the package we require has also been added to JCenter. We will fix the `build.gradle` in https://github.com/ooni/probe/issues/1191.

**Comment by bassosimone** [comment]
@licaon-kter AFAICT:

1. the gitlab pipeline [is now building probe-android](https://gitlab.com/fdroid/fdroiddata/-/commit/8c4c05d22b98f98c208e03fc6a741d249c839b8b)

2. my understanding is that version 2.5.0 is now supported by f-droid

3. yet, [the latest available version is 2.3.2](https://f-droid.org/en/packages/org.openobservatory.ooniprobe/)

Is there anything else we should do? Thanks!

**Comment by licaon-kter** [comment]
Yeah, how to fix this now https://f-droid.org/wiki/index.php?title=org.openobservatory.ooniprobe/lastbuild_61&oldid=271360 ? :)

**Comment by bassosimone** [comment]
So, maybe stupid question: where do I go straight to that link from https://f-droid.org/wiki/page/org.openobservatory.ooniprobe? Regarding the building failure, I'll route the question to @lorenzoPrimi, who knows better than me these details. Thanks for replying so quickly!

**Comment by licaon-kter** [comment]
The Wiki is obsolete since Dec 2018, so do not use that page.

Bookmark, current cycle: https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500

Your app: https://f-droid.org/wiki/index.php?title=org.openobservatory.ooniprobe/lastbuild or lastbuild_VERSIONCODE

**Comment by bassosimone** [comment]
@licaon-kter I opened a merge request that we think should fix the build: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7041

I am not sure however, whether this is enough to fix the problem in general, or whether changes need also to be implemented in other places.

**Comment by lorenzoPrimi** [comment]
This was caused from the fact that we added more build flavours and now the `fdroid` build is called `stableFdroid`
<img width="206" alt="Screenshot 2020-07-02 at 13 20 26" src="https://user-images.githubusercontent.com/1616097/86356746-0fc13980-bc6d-11ea-9d69-1bf20cd9ed80.png">

**Comment by bassosimone** [comment]
@licaon-kter it seems [the build failed](https://f-droid.org/wiki/index.php?title=org.openobservatory.ooniprobe/lastbuild_61&redirect=no). The error that I see in the wiki is:

> "could not bring up vm 'builder_default'"

The [pipeline build](https://gitlab.com/fdroid/fdroiddata/-/jobs/622060673#L189) also shows a file not found error:

```
Traceback (most recent call last):
  File "./issuebot.py", line 690, in <module>
    main()
  File "./issuebot.py", line 653, in main
    appids, builds = get_builds_in_merge_request(gl, merge_request)
  File "./issuebot.py", line 597, in get_builds_in_merge_request
    with open(metadata_file) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'metadata/io.simplelogin.android.fdroid.yml'
```

But it's unclear to me whether that's a fatal error.

**Comment by licaon-kter** [comment]
Ignore the bot and that specific error, it's a random infra issue.

Maybe next cycle will build it.

**Comment by bassosimone** [comment]
okay, thanks!
