### ISSUE TITLE
ERROR: Could not download tink-1.3.0-rc2.jar (com.google.crypto.tink:tink:1.3.0-rc2): No cached version available for offline mode

### ISSUE THREAD

**Issue by torch016** [ooni/probe-android#354]
I tried running the android app locally but it failed with the above error: ERROR: Could not download tink-1.3.0-rc2.jar (com.google.crypto.tink:tink:1.3.0-rc2): No cached version available for offline mode

**Comment by lorenzoPrimi** [comment]
@torch016  a quick search on google showed me that your problem is tied to your IDE and the offline mode being enabled.
Try this: https://stackoverflow.com/questions/62230787/android-studio-gradle-sync-failed-could-not-download-tink

**Comment by lorenzoPrimi** [comment]
or this https://stackoverflow.com/questions/22607661/no-cached-version-available-for-offline-mode

**Comment by bassosimone** [comment]
@torch016 did the above suggestions help you? I am going to close this issue for now. Please, reopen if needed!
