### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [ooni/probe-android#377]
https://f-droid.org/wiki/index.php?title=org.openobservatory.ooniprobe/lastbuild_65&oldid=280025

**Comment by bassosimone** [comment]
Thanks for reporting this issue. Today I learned why moving issues across repositories is not a good idea. Apologies for moving the original https://github.com/ooni/probe/issues/1255 off from this repository to the repository where we track all issues with our probes. I guess I should not be doing the same in the future.

Based on https://github.com/ooni/probe/issues/1255#issuecomment-707053976, I though no further action was required on our part. Is my understanding correct? Thanks again (in https://github.com/ooni/probe-android/pull/373 we're trying to setup CI such that we can know in advance if we're breaking the f-droid build).
