### ISSUE TITLE
Show high level stats about censored sites for web_connectivity

### ISSUE THREAD

**Issue by hellais** [ooni/probe-android#53]
It was requested by a user, but I think we had also discussed this internally, about exposing some view that shows some high level stats about how many sites were found to be blocked vs the number of sites not blocked.

This could be I guess integrated into some sort of dashboard.

**Comment by bassosimone** [comment]
I believe a good starting point to implement this could be in the view where sites are listed. Like, we can separate anomalous and non-anomalous. But we can also add a couple stats at the top.

Again, this seems to me something self contained enough to be possibly proposed as a topic for today's hackathon on OONI taking place here in Turin.

**Comment by hellais** [comment]
This is implemented in OONI Probe mobile 2.0 🎉
