### ISSUE TITLE
Separate anomalous websites from normal sites in result list

### ISSUE THREAD

**Issue by hellais** [ooni/probe-android#59]
It seems like users are confused as to what green/red means in the website list view.

We should probably add a separator between the anomalous and normal sites and write some text above indicating what it means.

See quick mockup:
![screen shot 2017-02-12 at 11 46 08 0000](https://cloud.githubusercontent.com/assets/424620/22861772/1859402e-f119-11e6-9b96-fa26720f17b7.png)

**Comment by bassosimone** [comment]
Yeah, I totally believe this would be useful. I think I'll propose this as a topic for [today's hackathon on OONI that will be hosted by Torino Hacknights](http://torino.hacknight.it/2017/05/30/ooni/).
