### ISSUE TITLE
web_connectivity: allow to visit specific URL

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-android#70]
User story: I am a user, I see that a site is an anomaly, I really can't believe it, and I want to see for myself whether that site is actually blocked, by opening it in the browser, and perhaps after that I may also want to provide some sort of feedback to the app developers.

[Edit: maybe this works best for the converse case where I see that a site is not treated as an anomaly, but I know it's somehow blocked in my country (i.e. with a blockpage) and I really want to check right away what I can see from my phone, and possibly report a false negative.]

xref: https://github.com/TheTorProject/ooniprobe-ios/issues/100

**Comment by lorenzoPrimi** [comment]
Fixed in the 2.0 app, now you can click an URL in the test result screen
