### ISSUE TITLE
Show only logs of a specific input

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-android#72]
User story: I am an advanced user, I have run a test, I have seen some anomalies and I'd like to understand more one of them, hence I'd like to see only logs related to such anomaly.

xref: https://github.com/measurement-kit/measurement-kit/issues/1160, https://github.com/TheTorProject/ooniprobe-ios/issues/102

**Comment by lorenzoPrimi** [comment]
Moved to https://github.com/ooni/probe/issues/821
