### ISSUE TITLE
More explicit "view log", like in iOS

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-android#73]
While replying to detailed feedback we received, I noticed that the feature for viewing logs is too much hidden on Android, as compared to iOS (see https://github.com/TheTorProject/ooniprobe-ios/issues/103 for a screenshot). It would be nice if, instead, it would be possible to view logs as easily as we do on iOS.

**Comment by lorenzoPrimi** [comment]
In the 2.x app there will be the button up there to view log, closing this and keepin the iOS ticket open for copy purposes
