### ISSUE TITLE
Test a random sample of URLs from all 31 categories (included in Citizen Lab repo)

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe-android#74]
Currently ooniprobe's mobile app tests a random sample of URLs from the Citizen Lab's global test list every time the user runs Web Connectivity. This means that, in some cases, users might only be testing pornographic sites (or other sites that might be of less interest to them), instead of testing "more interesting" sites (such as news media, human rights sites, etc.).

A quick fix to this problem could be re-configuring the web connectivity test to test a random sample of URLs that are fetched from all 31 categories (https://github.com/citizenlab/test-lists/blob/master/lists/00-LEGEND-new_category_codes.csv). That way, a user tests a little bit of everything every time he/she runs web connectivity.

**Comment by hellais** [comment]
I am not 100% sure we actually want to follow this logic.

The issues I can see with doing it this way is that category that have fewer sites belonging to them will be tested more often than those in categories with many more sites.
We may or may not want this.

I would love to hear what @bassosimone and @darkk think of this too, though.

**Comment by bassosimone** [comment]
I believe the best approach is to randomly sample from the global and local test lists. I think we should probably spend some time to have resources update in MK v0.7.0 so to have it inside next mobile release.

**Comment by lorenzoPrimi** [comment]
xref: https://github.com/ooni/probe-ios/issues/104
