### ISSUE TITLE
Overwrite resources after update

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-android#80]
As far as I can tell, after d88c285, resources are only copied if they're not present. This means that, after an upgrade, they are not overwritten, which is probably not what we want.

**Comment by hellais** [comment]
Is this still the case? Does this mean updates to test lists will not happen upon upgrade of the app?

cc @lorenzoPrimi

**Comment by lorenzoPrimi** [comment]
@bassosimone what is this?
Didn't you modified this function?

**Comment by bassosimone** [comment]
I did modify the function, however, the behavior is that, if they are present, they are not copied. To complete the work, we should probably have code that runs only after an update.

(When MK v0.5 will be shipped, it will integrate automatic updating of resources, but until then I guess we should implement a hook that runs only after an upgrade.)

**Comment by bassosimone** [comment]
@lorenzoPrimi: I guess this is still an issue, right? How do we want to proceed?

**Comment by lorenzoPrimi** [comment]
I thought you implemented something (either in java or mk)
So are we still looking for a solution?

**Comment by lorenzoPrimi** [comment]
@bassosimone have you integrated something in mk or should I do it in a native way?

**Comment by bassosimone** [comment]
native!

**Comment by bassosimone** [comment]
@lorenzoPrimi how are we planning to deal with this issue?

**Comment by lorenzoPrimi** [comment]
I guess we should address it in the 1.3 or 1.4, the version with all the testlists

**Comment by lorenzoPrimi** [comment]
Done in 2.0
