### ISSUE TITLE
Can't run tests automatically

### ISSUE THREAD

**Issue by ORARiccardo** [ooni/probe-android#89]
On my Android 7.0, when it's time to run scheduled tests I get no results and the following message: "the test has no results or it was aborted".

ooniprobe version 1.1.4

**Comment by ORARiccardo** [comment]
Still affected. Not sure if this can help to reproduce the bug: I set the time to midnight and I'm also using Twilight (not sure if the draw over other app could cause some issues).

I noticed that somehow, after unlocking the smartphone, ooniprobe was able to do the web-connectivity test — though it happened only once.

**Comment by lorenzoPrimi** [comment]
We are aware of this problem and we are monitoring this issue with events 
https://github.com/ooni/probe-android/commit/a8dbde15d763d7473d8b3b293da995ba19bbc9cc

Based on data we'll decide if keeping or removing this feature in the 2.0 app

**Comment by lorenzoPrimi** [comment]
Closing for now, this feature was removed from the app. Can be reintroduced but still not sure.
