### ISSUE TITLE
Settings seem to persist app deletion

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-android#97]
I deleted the app on my device. Then, installed another version of the app from Android Studio. I was not presented the on-boarding procedure and settings where already set. This led us to understand that the actual default for `probe_asn` was not correct (see: 22731da).

This issue with settings persisting is also the reason why I dismantled the copying of resources as it was implemented before and replaced it with the current checks on file existence.

**Comment by lorenzoPrimi** [comment]
Did some research on this topic and found this
https://stackoverflow.com/questions/15873066/how-to-remove-shared-preference-while-application-uninstall-in-android

> The problem is not with preferences. It's drastically the backup manager! .. since android-23 by default backup as a task stores app's data including preferences to cloud. Later when you uninstall then install newer version you are probably going to use restored preferences. 

Should we disable the cloud backup? and if yes why?

**Comment by bassosimone** [comment]
I guess the question regarding the cloud backup is probably more related to user's privacy or preference than on merely the settings. Thanks for explaining me what was going on.

I guess we need to devise a strategy for updating resources and the like robust to that.

**Comment by lorenzoPrimi** [comment]
I guess it's not something we would have to discuss. If an user has iCloud / Google cloud activated is because he wants all the app backups to be sent on the cloud, otherwise it's so easy to disable that option! :)

For updating resources we will use a timestamp. Will be integrated in the 1.1.6 version

**Comment by bassosimone** [comment]
>  If an user has iCloud / Google cloud activated is because he wants all the app backups to be sent on the cloud

I think the default matters and it's quite a shame the default is for sharing without users knowing. So, maybe we can say explicitly that settings are saved like this, to increase awareness?

**Comment by lorenzoPrimi** [comment]
This is not the default. There is no default as far as I remember, when you setup your phone this is a compulsory option to select.

**Comment by bassosimone** [comment]
Alright. What I wanted to say is that we _should_ probably tell users that settings _might_ be saved in the cloud and, as such, _might_ survive app deletion, isn't it?

**Comment by lorenzoPrimi** [comment]
Why? Any other app informs you about this?
If you manually select "backup my apps" on your phone settings I think it's pretty clear that you choose it.

**Comment by TeMuNiDe** [comment]
Many people uninstall and re-install apps when they mess up something they do not know. so, seeing same  mess after re installing may frustrate them. As a fellow android developer, I suggest removing that feature.

**Comment by bassosimone** [comment]
@TeMuNiDe yeah, I think your suggestion makes sense! 👍

**Comment by lorenzoPrimi** [comment]
Again: it's a phone setting, not an app setting.

**Comment by lorenzoPrimi** [comment]
Did some research, this is due to https://github.com/ooni/probe-android/blob/master/app/src/main/AndroidManifest.xml#L14

I'm not convinced this is a bug, for me is a feature! 
If you think it has to be set to false speak now :) @hellais @bassosimone

**Comment by lorenzoPrimi** [comment]
In the 2.0 app this is set to false
https://github.com/ooni/probe-android/blob/release/2.0.0/app/src/main/AndroidManifest.xml#L11

**Comment by hellais** [comment]
I am also not sure we want to disable the backup of settings, especially in light of the fact that the new app will have many more settings, that can take the user some amount of time to configure.

I would suggest setting `allowBackup=true` and if the user wants to disable them, they can do it from the system settings.

@elioqoshi what do you think?
